#https://mherman.org/blog/logging-in-kubernetes-with-elasticsearch-Kibana-fluentd/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      #nodeSelector:
      #  env: label
      terminationGracePeriodSeconds: 300
      initContainers:
      - image: alpine:3.6
        name: elasticsearch-logging-init
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - image: alpine:3.6
        name: increase-the-ulimit
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
        env:
        - name: cluster.name
          value: es-logging
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.type
          value: single-node
        - name: thread_pool.bulk.queue_size
          value: "500"
        - name: ES_JAVA_OPTS
          value: -Xms3g -Xmx3g
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
      volumes:
      - name: data
        hostPath:
          # id 1000
          path: /mnt/elasticsearch-data
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: db
  - port: 9300
    name: transport
