apiVersion: v1
kind: Secret
metadata:
  name: infra-appconfig-secret
  namespace: infra-pipeline-hml
stringData:
  application.properties: |-
    # Geral
    ## Valores aceitos: DEV, PRD
    ## NAO COLOCAR COMENTARIO APOS VALOR DA CHAVE. SE NECESSARIO COLOCAR COMENTARIO EM UMA NOVA LINHA
    aplicacao.ambiente=DEV
    aplicacao.tipo-storage=BD
    # JCR
    ## Define as credenciais do JCR-STORAGE conforme a estrutura interna do seu tribunal.
    aplicacao.jcr.url=xpto
    aplicacao.jcr.usuario=xpto
    aplicacao.jcr.senha=123
type: Opaque
